<?php
/**
 * @file
 * Exposes functionality for manually cropping an image.
 */

require_once 'manualcrop.effects.inc';
require_once 'manualcrop.widget.inc';

/**
 * Implements hook_help().
 */
function manualcrop_help($path) {
  switch ($path) {
    case 'admin/config/media/image-styles/edit/%':
      return '<p>' . t("<strong>Note:</strong> if you are using a manual crop effect, it's forced to be the only manual crop effect and first effect in the list.") . '</p>';
  }
}

/**
 * Implements hook_theme().
 */
function manualcrop_theme() {
  return array(
    'manualcrop_crop_and_scale_summary' => array(
      'variables' => array('data' => NULL),
    ),
    'manualcrop_crop_summary' => array(
      'variables' => array('data' => NULL),
    ),
    'manualcrop_overlay' => array(
      'variables' => array('fid' => NULL, 'path' => NULL),
    ),
    'manualcrop_widget' => array(
      'render element' => 'element',
    ),
  );
}

/**
 * Form Builder; Configuration settings for manual crop and scale effect.
 *
 * @param $data
 *   The current configuration for this manual crop and scale effect.
 */
function manualcrop_crop_and_scale_form($data) {
  $form = image_scale_form($data);

  $form['width']['#required'] = TRUE;
  $form['height']['#required'] = TRUE;

  $form['respectminimum'] = array(
    '#type' => 'checkbox',
    '#default_value' => (isset($data['respectminimum'])) ? $data['respectminimum'] : 0,
    '#title' => t('Respect minimum'),
    '#description' => t("Make sure the selected crop area is at least as big as the destination size. This doesn't enforce minimum image dimensions."),
  );

  return $form;
}

/**
 * Returns HTML for a summary of an image manual crop and scale effect.
 *
 * @param $variables
 *   An associative array containing:
 *   - data: The current configuration for this manual crop and scale effect.
 *
 * @ingroup themeable
 */
function theme_manualcrop_crop_and_scale_summary($variables) {
  $data = $variables["data"];
  $str = check_plain($data['width']) . 'x' . check_plain($data['height']);

  if ($data['upscale'] || $data['respectminimum']) {
    $str .= ' (' . ($data['upscale'] ? t('upscaling allowed') : '');
    $str .= ($data['upscale'] && $data['respectminimum'] ? ' ' . t('and') . ' ' : '');
    $str .= ($data['respectminimum'] ? t('crop minimum dimensions') : '') . ')';
  }

  return $str;
}

/**
 * Form Builder; Configuration settings for manual crop effect.
 *
 * @param $data
 *   The current configuration for this manual crop effect.
 */
function manualcrop_crop_form($data) {
  $form = image_resize_form($data);

  $form['width']['#required'] = FALSE;
  $form['width']['#title'] = t('Minimum crop width');
  $form['width']['#description'] = t("Only applied if a user tries to crop, this enforces no minimum image width!");

  $form['height']['#required'] = FALSE;
  $form['height']['#title'] = t('Minimum crop height');
  $form['height']['#description'] = t("Only applied if a user tries to crop, this enforces no minimum image height!");

  return $form;
}

/**
 * Returns HTML for a summary of an image resize effect.
 *
 * @param $variables
 *   An associative array containing:
 *   - data: The current configuration for this resize effect.
 *
 * @ingroup themeable
 */
function theme_manualcrop_crop_summary($variables) {
  $data = $variables['data'];

  if ($data['width'] && $data['height']) {
    return ' (' . t('minimum crop dimensions ') . ' ' . check_plain($data['width']) . 'x' . check_plain($data['height']) . ')';
  }
  elseif ($data['width'] || $data['height']) {
    return ' (' . ($data['width']) ? t('minimum crop width @width', array('@width' => $data['width'])) : t('minimum crop height @height', array('@height' => $data['height'])) . ')';
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function manualcrop_form_image_effect_form_alter(&$form, &$form_state) {
  if (!is_array($form['#submit'])) {
    $form['#submit'] = array('image_effect_form_submit');
  }

  // If it's a manual crop effect do a custom submit handler first.
  // Otherwise reorder the effects after the submit.
  if ($form_state['image_effect']['module'] == 'manualcrop') {
    array_unshift($form['#submit'], 'manualcrop_image_effect_form_submit');
  }
  elseif (!empty($form_state['image_style']['effects'])) {
    $form['#submit'][] = 'manualcrop_force_effect_order';
  }
}

/**
 * Effect form submit handler; Sets the image style id and weight of the effect.
 *
 * @param $form
 *   Effect form array.
 * @param $form_state
 *   Form state array.
 */
function manualcrop_image_effect_form_submit($form, &$form_state) {
  $style = $form_state['image_style'];
  $effect = $form_state['image_effect'];

  // Set style id so the effect can use it.
  $form_state['values']['data']['isid'] = $style['isid'];

  if (count($style['effects']) == 0) {
    // First effect, so weight is 0.
    $form_state['values']['weight'] = 0;
  }
  elseif (!isset($effect['ieid'])) {
    // New effect, weight must be the weight of the first one minus 1.
    $first = reset($style['effects']);
    $form_state['values']['weight'] = $first["weight"] - 1;
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function manualcrop_form_image_effect_delete_form_alter(&$form, &$form_state) {
  if (!is_array($form['#submit'])) {
    $form['#submit'] = array('image_effect_delete_form_submit');
  }

  // If it's a manual crop effect do a custom submit handler to cleanup the cropped areas.
  if ($form_state['image_effect']['module'] == 'manualcrop') {
    array_unshift($form['#submit'], 'manualcrop_image_effect_delete_form_submit');
  }
}

/**
 * Effect deletion form submit handler; Cleanup old selection areas.
 *
 * @param $form
 *   Effect form array.
 * @param $form_state
 *   Form state array.
 */
function manualcrop_image_effect_delete_form_submit($form, &$form_state) {
  manualcrop_image_style_delete($form_state['image_style']);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function manualcrop_form_image_style_form_alter(&$form, &$form_state) {
  $style = $form_state['image_style'];

  if (!empty($style['effects'])) {
    if (!is_array($form['#submit'])) {
      $form['#submit'] = array('image_style_form_submit');
    }

    // Reorder effects on submit.
    $form['#submit'][] = 'manualcrop_force_effect_order';

    // Filter all manual crop effects out of the form if there's already a manual crop effect.
    if (isset($form['effects']['new']['new'])) {
      foreach ($style['effects'] as $effect) {
        if ($effect['module'] == 'manualcrop') {
          $form['effects']['new']['new']['#options'] = array_diff_key($form['effects']['new']['new']['#options'], manualcrop_image_effect_info());
          break;
        }
      }
    }
  }
}

/**
 * Effect and style form submit handler; Force the manual crop effect to be the first one.
 *
 * @param $form
 *   Effect or style form array.
 * @param $form_state
 *   Form state array.
 */
function manualcrop_force_effect_order($form, &$form_state) {
  // In both forms (style and effect) we find the style in the same key.
  // The style array is received trough the loader to make sure the function
  // works with the latest version.
  $style = $form_state['image_style'];
  $style = image_style_load(NULL, $style['isid']);

  if (!empty($style['effects'])) {
    foreach ($style['effects'] as $eid => $effect) {
      if ($effect['module'] == 'manualcrop') {
        $first = reset($style['effects']);

        if ($eid != key($style['effects'])) {
          // Change the weight of this effect to the weight of the first effect minus 1.
          $effect['weight'] = $first['weight'] - 1;
          image_effect_save($effect);
        }

        break;
      }
    }
  }
}

/**
 * Implements hook_image_style_delete().
 */
function manualcrop_image_style_delete($style) {
  db_delete('manualcrop')
    ->condition('isid', $style['isid'])
    ->execute();
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function manualcrop_form_node_form_alter(&$form, &$form_state, $form_id) {
  $form['#validate'][] = 'manualcrop_validate_crop_selection';
  $form['#submit'][] = 'manualcrop_save_crop_selection';

  if (!isset($form_state['manualcrop_widget_data'])) {
    $form_state['manualcrop_widget_data'] = array('images' => array());
  }
}

/**
 * Node form validation handler; Check the cropped selection.
 *
 * @param $form
 *   Node form array.
 * @param $form_state
 *   Form state array.
 */
function manualcrop_validate_crop_selection($form, &$form_state) {
  if (!empty($form_state['manualcrop_widget_data']['images'])) {
    // Create a new selections key in the data array, this is some kind of cache.
    $form_state['manualcrop_widget_data']['selections'] = array();
    $save = &$form_state['manualcrop_widget_data']['selections'];

    // Loop trough the positions to get the manualcrop data.
    foreach ($form_state['manualcrop_widget_data']['images'] as $image) {
      $value = $form_state['values'];

      foreach ($image['parents'] as $key) {
        $value = $value[$key];
      }

      // Create a selections array for the current image, the first element is the path
      // to the original image, needed for flushing the cache.
      $save[$value['fid']] = array(
        'path' => $image['uri'],
        'styles' => array(),
      );
      $first = TRUE;

      foreach ($value['manualcrop_selection'] as $isid => $selection) {
        if (!empty($selection)) {
          if (preg_match('/^([0-9]+\|){3}[0-9]+$/', $selection)) {
            $selection = array_map('intval', explode('|', $selection));

            // Check position and minimum dimensions.
            if ($selection[0] >= 0 && $selection[1] >= 0 && $selection[2] > 0 && $selection[3] > 0) {
              // Check if the selections fits on the image.
              if (($selection[0] + $selection[2]) <= $image['width'] && ($selection[1] + $selection[3]) <= $image['height']) {
                $save[$value['fid']]['styles'][$isid] = array(
                  'x' => $selection[0],
                  'y' => $selection[1],
                  'width' => $selection[2],
                  'height' => $selection[3],
                );
                continue;
              }
            }
          }

          $style = image_style_load(NULL, $isid);

          if ($first) {
            $key = implode('][', $image['parents']) . '][manualcrop_style';
          }
          else {
            $key = implode('][', $image['parents']) . '][manualcrop_selection][' . $isid;
          }

          form_set_error($key, t('The crop selection for %filename (@style image style) is invalid, please clear it or reselect.', array(
            '@style' => $style['name'],
            '%filename' => $image['filename']
          )));

          $first = FALSE;
        }
      }
    }
  }
}

/**
 * Node form submit handler; Save the cropped selection.
 *
 * @param $form
 *   Node form array.
 * @param $form_state
 *   Form state array.
 */
function manualcrop_save_crop_selection($form, &$form_state) {
  if (!empty($form_state['manualcrop_widget_data']['selections'])) {


    // Loop trough the selections to save them. $styles can by an empty array, but we loop trough
    // the whole array to delete old selections.
    foreach ($form_state['manualcrop_widget_data']['selections'] as $fid => $data) {
      db_delete('manualcrop')
        ->condition('fid', $fid)
        ->execute();

      foreach ($data['styles'] as $isid => $selection) {
        db_insert('manualcrop')
          ->fields(array_merge($selection, array(
            'fid' => $fid,
            'isid' => $isid,)
          ))
          ->execute();
      }

      // Clear the cached versions of this image.
      image_path_flush($data['path']);
    }
  }
}

/**
 * Implements hook_file_delete().
 */
function manualcrop_file_delete($file) {
  db_delete('manualcrop')->condition('fid', $file->fid)->execute();
}

/**
 * Gets the crop area for an image.
 *
 * @param $file
 *   Path to an image file.
 * @param $isid
 *   Image style id, or 0 for all styles.
 * @return
 *   An object defining the cropping area with following items:
 *   - "x": An integer representing the top left corner's x-position in pixels.
 *   - "y": An integer representing the top left corner's y-position in pixels.
 *   - "width": An integer representing the width in pixels.
 *   - "height": An integer representing the height in pixels.
 *   If $isid was 0 an object with all the styles is returned.
 */
function manualcrop_load_crop_selection($file, $isid = 0) {
  if ($isid == 0) {
    $result = db_query('SELECT c.isid, c.x, c.y, c.width, c.height FROM {manualcrop} c INNER JOIN {file_managed} f ON c.fid = f.fid WHERE f.uri = :uri', array(
      ':uri' => $file,
    ));

    return $result;
  }
  else {
    $result = db_query('SELECT c.x, c.y, c.width, c.height FROM {manualcrop} c INNER JOIN {file_managed} f ON c.fid = f.fid WHERE c.isid = :isid AND f.uri = :uri', array(
      ':isid' => $isid,
      ':uri' => $file,
    ));

    foreach ($result as $record) {
      return $record;
    }
  }

  return NULL;
}

/**
 * Returns the styles that have crop settings.
 *
 * @return
 *   An array of styles with the style name as key and containing:
 *   - "isid": The style id.
 *   - "effect": The effect data.
 */
function manualcrop_get_styles_with_crop() {
  $hascrop = &drupal_static(__FUNCTION__, array());

  if(empty($hascrop)) {
    $styles = image_styles();

    foreach ($styles as $name => $style) {
      if (!empty($style['effects'])) {
        $effect = reset($style['effects']);

        if ($effect['module'] == 'manualcrop') {
          // The first effect is a manual crop effect.
          $hascrop[$name] = $effect;
        }
      }
    }
  }

  return $hascrop;
}